import { useEffect, useRef, useState } from 'react';
import { Copy, Download, RotateCcw } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Separator } from '@/components/ui/separator';
import { Slider } from '@/components/ui/slider';

const fonts = ['Inter','Roboto','Open Sans','Lato','Montserrat','Merriweather','Source Sans 3','Source Serif 4','Playfair Display','IBM Plex Sans','IBM Plex Serif','DM Sans','Nunito Sans','Noto Sans','Noto Serif','Libre Baskerville','Fira Sans','Fira Code','JetBrains Mono','Roboto Mono'];
const defaults = {page:{size:'a4',margins:{top:'20mm',right:'30mm',bottom:'20mm',left:'30mm'}},typography:{bodyFont:'inherit',headingFont:'inherit',monoFont:'inherit',fontSize:'11pt',lineHeight:1.5,justify:'left',googleFonts:{} as Record<string,string>},colors:{text:'#1a1a1a',heading:'#111111',link:'#0b57d0',muted:'#666666',accent:'#0b57d0',surface:'#f8f8f8',border:'#d8d8d8'},spacing:{paragraph:'7pt',headingTop:'18pt',headingBottom:'7pt',listIndent:'18pt'},headings:{weight:'bold',h1Size:'18pt',h2Size:'15pt',h3Size:'13pt'},tables:{cellPadding:'5pt',borderWidth:'0.5pt',striped:true,headerBackground:'#eeeeee'},blocks:{padding:'9pt',radius:'3pt',quoteBorderWidth:'3pt'}};
type Theme = typeof defaults;
const fontCss = `https://fonts.googleapis.com/css2?${fonts.map(f=>`family=${encodeURIComponent(f)}:wght@400;700`).join('&')}&display=swap`;

export default function App(){
  const [theme,setTheme]=useState<Theme>(()=>structuredClone(defaults)); const [pdf,setPdf]=useState(''); const [status,setStatus]=useState('Rendering…'); const [error,setError]=useState(''); const version=useRef(0);
  useEffect(()=>{const link=document.createElement('link');link.rel='stylesheet';link.href=fontCss;document.head.append(link);return()=>link.remove()},[]);
  useEffect(()=>{const timer=setTimeout(async()=>{const own=++version.current;setStatus('Rendering…');setError('');try{const response=await fetch('/render',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({theme})});if(!response.ok)throw new Error((await response.json()).error);const url=URL.createObjectURL(await response.blob());if(own!==version.current)return URL.revokeObjectURL(url);setPdf(old=>{if(old)URL.revokeObjectURL(old);return url});setStatus('Ready')}catch(e){setStatus('Error');setError(e instanceof Error?e.message:String(e))}},450);return()=>clearTimeout(timer)},[theme]);
  const update=(path:string,value:unknown)=>setTheme(current=>{const next=structuredClone(current) as any;const keys=path.split('.');let target=next;for(const key of keys.slice(0,-1))target=target[key];target[keys.at(-1)!]=value;return next});
  const number=(path:string)=>Number(path.split('.').reduce<any>((v,k)=>v[k],theme).replace(/[^0-9.]/g,''));
  const slider=(label:string,path:string,min:number,max:number,step=1,unit='mm')=><Slider label={label} value={number(path)} min={min} max={max} step={step} suffix={` ${unit}`} onChange={e=>update(path,`${e.currentTarget.value}${unit}`)}/>;
  const fontSelect=(label:string,role:'body'|'heading'|'mono')=>{const value=theme.typography.googleFonts[role]||'inherit';return <div className="grid gap-2"><Label>{label}</Label><Select value={value} onValueChange={font=>{setTheme(current=>{const next=structuredClone(current);if(font==='inherit'){delete next.typography.googleFonts[role];(next.typography as any)[`${role}Font`]='inherit'}else{next.typography.googleFonts[role]=font;(next.typography as any)[`${role}Font`]=font}return next})}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="inherit">Leafmark default</SelectItem>{fonts.map(font=><SelectItem key={font} value={font}><span style={{fontFamily:font}}>{font} — Aa Bb Cc</span></SelectItem>)}</SelectContent></Select></div>};
  const config=JSON.stringify({theme},null,2); const download=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([config+'\n'],{type:'application/json'}));a.download='config.json';a.click()};
  return <main className="grid h-full grid-cols-[minmax(420px,1fr)_420px] max-[850px]:grid-cols-1 max-[850px]:grid-rows-[55vh_auto]">
    <section className="bg-neutral-700 p-5"><div className="relative h-full overflow-hidden rounded-lg bg-white shadow-2xl">{pdf?<iframe className="h-full w-full border-0" src={pdf}/>:<div className="grid h-full place-items-center text-muted-foreground">Rendering example PDF…</div>}</div></section>
    <aside className="overflow-y-auto border-l bg-background"><header className="sticky top-0 z-20 border-b bg-background/95 p-5 backdrop-blur"><div className="flex items-center justify-between"><div><h1 className="text-lg font-semibold">Theme editor</h1><p className="text-xs text-muted-foreground">{status}</p></div><div className="flex gap-2"><Button size="icon" variant="outline" onClick={()=>navigator.clipboard.writeText(config)}><Copy/></Button><Button size="icon" variant="outline" onClick={download}><Download/></Button><Button size="icon" variant="outline" onClick={()=>setTheme(structuredClone(defaults))}><RotateCcw/></Button></div></div>{error&&<p className="mt-3 rounded-md bg-destructive/10 p-2 text-xs text-destructive whitespace-pre-wrap">{error}</p>}</header>
    <div className="space-y-4 p-5">
      <Card><CardHeader><CardTitle>Page</CardTitle></CardHeader><CardContent className="space-y-4"><Select value={theme.page.size} onValueChange={v=>update('page.size',v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="a4">A4</SelectItem><SelectItem value="letter">Letter</SelectItem></SelectContent></Select>{slider('Top margin','page.margins.top',5,60)}{slider('Right margin','page.margins.right',5,60)}{slider('Bottom margin','page.margins.bottom',5,60)}{slider('Left margin','page.margins.left',5,60)}</CardContent></Card>
      <Card><CardHeader><CardTitle>Typography</CardTitle></CardHeader><CardContent className="space-y-4">{fontSelect('Body font','body')}{fontSelect('Heading font','heading')}{fontSelect('Code font','mono')}<Separator/>{slider('Font size','typography.fontSize',8,18,.5,'pt')}<div className="grid gap-2"><Label>Alignment</Label><Select value={theme.typography.justify} onValueChange={v=>update('typography.justify',v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="left">Left aligned</SelectItem><SelectItem value="justify">Justified</SelectItem></SelectContent></Select></div></CardContent></Card>
      <Card><CardHeader><CardTitle>Spacing</CardTitle></CardHeader><CardContent className="space-y-4">{slider('Paragraph spacing','spacing.paragraph',0,24,1,'pt')}{slider('Before headings','spacing.headingTop',0,40,1,'pt')}{slider('After headings','spacing.headingBottom',0,24,1,'pt')}{slider('List indent','spacing.listIndent',4,40,1,'pt')}</CardContent></Card>
      <Card><CardHeader><CardTitle>Colors</CardTitle></CardHeader><CardContent className="grid grid-cols-2 gap-3">{Object.entries(theme.colors).map(([key,value])=><div className="grid gap-1" key={key}><Label className="capitalize">{key}</Label><Input type="color" value={value} onChange={e=>update(`colors.${key}`,e.target.value)}/></div>)}</CardContent></Card>
      <Card><CardHeader><CardTitle>Tables & blocks</CardTitle></CardHeader><CardContent className="space-y-4">{slider('Cell padding','tables.cellPadding',0,20,1,'pt')}{slider('Table border','tables.borderWidth',0,3,.25,'pt')}{slider('Block padding','blocks.padding',0,24,1,'pt')}{slider('Corner radius','blocks.radius',0,16,1,'pt')}{slider('Quote border','blocks.quoteBorderWidth',0,10,1,'pt')}</CardContent></Card>
    </div></aside></main>
}
